[build-system]
requires = [
  "setuptools>=68",
  "wheel",
  "pybind11>=2.11"
]
build-backend = "setuptools.build_meta"

[project]
name = "gridoptim"
version = "1.0.0"
description = "Fast grid search optimizer implemented in C++ with pybind11"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  {name = "Akhil Shimna Kumar"}
]

license = {text = "Proprietary"}

keywords = [
  "optimization",
  "grid search",
  "hyperparameter search",
  "pybind11"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: C++",
  "Operating System :: OS Independent"
]

[tool.cibuildwheel]
build = "cp310-* cp311-* cp312-* cp313-* cp314-*"
skip = "*-musllinux_*"
test-command = "python -c \"from gridoptim import GridOptim; print(GridOptim)\""
